<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
  <meta name="author" content="GeeksLabs">
  <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
  <link rel="shortcut icon" href="img/favicon.png">
<link media="all" type="text/css" rel="stylesheet"href="http://localhost/login/public/css/bootstrap.min.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/css/bootstrap-theme.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/css/elegant-icons-style.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/css/font-awesome.min.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/assets/fullcalendar/fullcalendar/fullcalendar.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/css/owl.carousel.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/css/jquery-jvectormap-1.2.2.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/css/fullcalendar.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/css/widgets.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/css/style.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/css/style-responsive.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/css/xcharts.min.css"> <link media="all" type="text/css" rel="stylesheet" href="http://localhost/login/public/css/jquery-ui-1.10.4.min.css">
  @yield('header') 
</head>
<body> 
  @include('admin.header.header')
  @include('admin.sidebar.sidebar')

  <section id="" class="" style="margin-left:20%;">
  @yield('member')
  @yield('memdetail')
  </section>
 <script src="http://localhost/login/public/js/jquery.js"></script> <script src="http://localhost/login/public/js/jquery-ui-1.10.4.min.js"></script> <script src="http://localhost/login/public/js/jquery-1.8.3.min.js"></script> <script src="http://localhost/login/public/js/jquery-ui-1.9.2.custom.min.js"></script> <script src="http://localhost/login/public/js/bootstrap.min.js"></script> <script src="http://localhost/login/public/js/jquery.scrollTo.min.js"></script> <script src="http://localhost/login/public/js/jquery.nicescroll.js"></script> <script src="http://localhost/login/public/assets/jquery-knob/js/jquery.knob.js"></script> <script src="http://localhost/login/public/js/jquery.sparkline.js"></script> <script src="http://localhost/login/public/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script> <script src="http://localhost/login/public/js/owl.carousel.js"></script> <script src="http://localhost/login/public/js/fullcalendar.min.js"></script> <script src="http://localhost/login/public/assets/fullcalendar/fullcalendar/fullcalendar.js"></script> <script src="http://localhost/login/public/js/calendar-custom.js"></script> <script src="http://localhost/login/public/js/jquery.rateit.min.js"></script> <script src="http://localhost/login/public/js/jquery.customSelect.min.js"></script> <script src="http://localhost/login/public/assets/chart-master/Chart.js"></script> <script src="http://localhost/login/public/js/scripts.js"></script> <script src="http://localhost/login/public/js/sparkline-chart.js"></script> <script src="http://localhost/login/public/js/easy-pie-chart.js"></script> <script src="http://localhost/login/public/js/jquery-jvectormap-1.2.2.min.js"></script> <script src="http://localhost/login/public/js/jquery-jvectormap-world-mill-en.js"></script> <script src="http://localhost/login/public/js/xcharts.min.js"></script> <script src="http://localhost/login/public/js/jquery.autosize.min.js"></script> <script src="http://localhost/login/public/js/jquery.placeholder.min.js"></script> <script src="http://localhost/login/public/js/gdp-data.js"></script> <script src="http://localhost/login/public/js/morris.min.js"></script> <script src="http://localhost/login/public/js/sparklines.js"></script> <script src="http://localhost/login/public/js/charts.js"></script> <script src="http://localhost/login/public/js/jquery.slimscroll.min.js"></script>
</body>
</html>